# Generated by Django 5.0.3 on 2024-07-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("city", models.CharField(max_length=50, verbose_name="City")),
                (
                    "instagram",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, null=True, verbose_name="Twitter"),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, null=True, verbose_name="Linkedin"),
                ),
                (
                    "telegram",
                    models.URLField(blank=True, null=True, verbose_name="Telegram"),
                ),
                ("site", models.URLField(blank=True, null=True, verbose_name="Site")),
                (
                    "github",
                    models.URLField(blank=True, null=True, verbose_name="Github"),
                ),
                (
                    "gitlab",
                    models.URLField(blank=True, null=True, verbose_name="Gitlab"),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resume/",
                        verbose_name="Resume",
                    ),
                ),
                (
                    "resume_url",
                    models.URLField(blank=True, null=True, verbose_name="Resume URL"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school", models.CharField(max_length=255, verbose_name="School")),
                ("degree", models.CharField(max_length=255, verbose_name="Degree")),
                (
                    "field_of_study",
                    models.CharField(max_length=255, verbose_name="Field of Study"),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("company", models.CharField(max_length=255, verbose_name="Company")),
                ("degree", models.CharField(max_length=255, verbose_name="Degree")),
                ("location", models.CharField(max_length=255, verbose_name="Location")),
                (
                    "start_date",
                    models.CharField(max_length=255, verbose_name="Start Date"),
                ),
                ("end_date", models.CharField(max_length=255, verbose_name="End Date")),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
            },
        ),
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("subtitle", models.CharField(max_length=255, verbose_name="subtitle")),
                ("description", models.TextField(verbose_name="description")),
                ("image", models.ImageField(upload_to="home/", verbose_name="image")),
            ],
            options={
                "verbose_name": "home",
                "verbose_name_plural": "home",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("percentage", models.PositiveIntegerField(verbose_name="percentage")),
                ("image", models.ImageField(upload_to="skills/", verbose_name="image")),
            ],
            options={
                "verbose_name": "skill",
                "verbose_name_plural": "skills",
            },
        ),
        migrations.CreateModel(
            name="Support",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "answer",
                    models.TextField(blank=True, null=True, verbose_name="Answer"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Is Read")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("my_role", models.CharField(max_length=255, verbose_name="My Role")),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "description",
                    models.ImageField(upload_to="projects/", verbose_name="Image"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "tools",
                    models.ManyToManyField(to="portfolio.skill", verbose_name="Tools"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
